defaultAssertionDataset:  gmp_quality
defaultLocation: US
defaultProject: intuitive-web-ga4-bigquery
vars:
  OUTPUT_PROJECT: pd-strategy
  GA4_DATASET: analytics_273569072
  LOCAL_TIMEZONE: America/New_York
  QUALITY_DATASET: gmp_quality
  TRANSFORMATIONS_DATASET: gmp_base 
  OUTPUTS_DATASET: gmp_outputs 
  REPORTING_DATASET: gmp_reporting 

